---

- hosts: all
  tasks:

  - name: install apache and php for OL7
    become: yes
    become_user: root
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
