---

- hosts: all
  tasks:

  - name: update repository index
    yum:
      update_cache: yes  
  
  - name: install apache2 package
    become: yes
    become_user: root
    yum:
      name: httpd
      state: absent

  - name: add php support for apache
    become: yes
    become_user: root
    yum:
      name: php
      state: absent
