---

- hosts: all
  become: yes
  pre_tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: update repository index (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: no
    when: ansible_distribution == "CentOS"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: no
    when: ansible_distribution == "Ubuntu"

  - name: update repository index (Oracle Linux)
    tags: always
    yum:
      update_cache: yes
    changed_when: no
    when: ansible_distribution == "RedHat"

- hosts: all
  become: yes
  roles:
    - base

- hosts: workstations
  become: yes
  roles:
    - workstations

- hosts: web_servers
  become: yes
  roles:
    - web_servers

- hosts: db_servers
  become: yes
  roles:
    - db_servers

- hosts: file_servers
  become: yes
  roles:
    - file_servers
