- name: install apache and php for Ubuntu servers
  tags: apache,ubuntu,apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for Oracle servers
  tags: apache,php,oracle
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "OracleLinux"

- name: start and enable httpd (Oracle)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "OracleLinux"

- name: change e-mail address for admin
  tags: apache,oracle,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "OracleLinux"
  register: httpd

- name: restart httpd (OracleLinux)
  tags: apache, oraclelinux, httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,oraclelinux,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
